executable = att.sh
Arguments = "$(cmd)"

log = /data/condor_builds/users/avijai/RNO/tutorials-rnog/get_daqstatus/logs/$(job_name).log
output = /data/condor_builds/users/avijai/RNO/tutorials-rnog/get_daqstatus/logs/$(job_name).out
error = /data/condor_builds/users/avijai/RNO/tutorials-rnog/get_daqstatus/logs/$(job_name).err

request_memory = 2000MB
request_disk = 1000MB
request_gpus=1

Universe        = vanilla
Notification    = never

queue
